<a href="https://colab.research.google.com/github/xersuy/pandas_10min_study/blob/main/pandas_10min_class_09_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Handling Missing Data
## **fillna, dropna**


* filna 데이터를 채우는 것 
* dropna 데이터를 버리는 것

In [ ]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame([[np.nan, 2, np.nan, 0], [3, 4, np.nan, 1],
                   [np.nan, np.nan, np.nan, 5]],
                  columns=list('ABCD'))

df

     A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5

In [8]:
#  dropna 데이터를 버리는 것
"""
  axis 는 1 컬럼을 의미 , 0 로우를 의미
  how 는 전부 null 일 때 drop을 시킨다.
"""
df.dropna(axis=1, how='all')

     A    B  D
0  NaN  2.0  0
1  3.0  4.0  1
2  NaN  NaN  5

In [9]:
"""
how='any'는 하나라도 null 값이 있다면 drop을 시킨다.
"""
df.dropna(axis=1, how='any')

   D
0  0
1  1
2  5

In [10]:
df.dropna(axis=0, how='all')

     A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5

In [11]:
df.dropna(axis=0, how='any')

Empty DataFrame
Columns: [A, B, C, D]
Index: []

In [13]:
df.fillna(0)

     A    B    C  D
0  0.0  2.0  0.0  0
1  3.0  4.0  0.0  1
2  0.0  0.0  0.0  5

In [14]:
values = {'A': 0, 'B': 1, 'C': 2, 'D': 3}
values

{'A': 0, 'B': 1, 'C': 2, 'D': 3}

In [15]:
df.fillna(value=values)

     A    B    C  D
0  0.0  2.0  2.0  0
1  3.0  4.0  2.0  1
2  0.0  1.0  2.0  5

In [18]:
df['D'].mean()

2.0

In [25]:
fill_na_value = df['D'].max()
fill_na_value

5

In [27]:
df.fillna(fill_na_value)

     A    B    C  D
0  5.0  2.0  5.0  0
1  3.0  4.0  5.0  1
2  5.0  5.0  5.0  5

In [28]:
df.isnull()

       A      B     C      D
0   True  False  True  False
1  False  False  True  False
2   True   True  True  False

In [29]:
df.isnull().sum()

A    2
B    1
C    3
D    0
dtype: int64

In [30]:
df.notnull().sum()

A    1
B    2
C    0
D    3
dtype: int64