<a href="https://colab.research.google.com/github/xersuy/pandas_10min_study/blob/main/pandas_10min_class_03_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://www.youtube.com/watch?v=XS-eOEUZQKM

subset observations 
특정 행만 뽑아서 데이터 프레임화를 한다.

In [2]:
import pandas as pd

In [9]:
df = pd.DataFrame(
            {
              "a" : [4, 5, 6],
              "b" : [7, 8, 9],
              "c" : [10, 11, 12]
            },
            index = pd.MultiIndex.from_tuples(
              [('d', 1),('d', 2),('e', 2)], 
              names=['n', 'v'])
            )
df

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [6]:
"""
df에 length 라는 컬럼이 없기 때문에 에러가 남.
"""
df[df.length > 7]

AttributeError: ignored

In [7]:
"""
a 컬럼에 7보다 큰 값이 없다.
"""
df[df.a > 7]

Empty DataFrame
Columns: [a, b, c]
Index: []

In [8]:
df[df.a < 7]

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [10]:
df.a > 7

n  v
d  1    False
   2    False
e  2    False
Name: a, dtype: bool

In [11]:
df[df['c'] > 7]

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12

In [18]:

# 중복된 값들을 추가
df = pd.DataFrame(
            {
              "a" : [4, 5, 6, 6],
              "b" : [7, 8, 9, 9],
              "c" : [10, 11, 12, 12]
            },
            index = pd.MultiIndex.from_tuples(
              [('d', 1),('d', 2),('e', 2),('e', 3)], 
              names=['n', 'v'])
            )
df

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12
  3  6  9  12

In [24]:
# 중복된 데이터를 제거
df = df.drop_duplicates()

df

     a  b   c
n v
d 1  4  7  10
  2  5  8  11
e 2  6  9  12