<a href="https://colab.research.google.com/github/xersuy/pandas_10min_study/blob/main/pandas_10min_class_13_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reshaping Data
**pd.concat([df1, df2])시리즈, 데이터프레임 합치기**

In [2]:
import pandas as pd
import numpy as np

In [5]:
s1 = pd.Series(['a', 'b'])
s1

0    a
1    b
dtype: object

In [8]:
s2 = pd.Series(['c', 'd'])
s2

0    c
1    d
dtype: object

pd.concat([s1, s2], ignore_index=True)

In [14]:
pd.concat([s1, s2], keys=['s1', 's2'],names=['Series name', 'Row ID'])

Series name  Row ID
s1           0         a
             1         b
s2           0         c
             1         d
dtype: object

In [19]:
df1 = pd.DataFrame([['a', 1], ['b', 2]],
                    columns=['letter', 'number'])
df1

  letter  number
0      a       1
1      b       2

In [20]:
df2 = pd.DataFrame([['c', 3], ['d', 4]],
                   columns=['letter', 'number'])
df2

  letter  number
0      c       3
1      d       4

In [21]:
pd.concat([df1, df2])

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [23]:
df3 = pd.DataFrame([['c', 3, 'cat'], ['d', 4, 'dog']],
                   columns=['letter', 'number', 'animal'])
df3

  letter  number animal
0      c       3    cat
1      d       4    dog

In [26]:
pd.concat([df1,df3] )

  letter  number animal
0      a       1    NaN
1      b       2    NaN
0      c       3    cat
1      d       4    dog

In [27]:
pd.concat([df1, df3], join='inner')

  letter  number
0      a       1
1      b       2
0      c       3
1      d       4

In [29]:
df4 = pd.DataFrame([['bird', 'polly'], ['monkey', 'george']],
                   columns=['animal', 'name'])
df4

   animal    name
0    bird   polly
1  monkey  george

In [30]:
df5 = pd.DataFrame([1], index=['a'])
df5

   0
a  1

In [31]:
df6 = pd.DataFrame([2], index=['a'])
df6

   0
a  2

In [34]:
# 같은 a 인덱스가 있어서 에러가 나온다.
pd.concat([df5, df6], verify_integrity=True)

ValueError: ignored

In [33]:
pd.concat([df5, df6])

   0
a  1
a  2