<a href="https://colab.research.google.com/github/xersuy/pandas_10min_study/blob/main/pandas_10min_class_05_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
import numpy as np
df = pd.DataFrame(
            {
              "a" : [4, 5, 6, 6, np.nan],
              "b" : [7, 8, np.nan, 9, 9],
              "c" : [10, 11, 12,np.nan, 12]
            },
            index = pd.MultiIndex.from_tuples(
              [('d', 1),('d', 2),('e', 2),('e', 3),('e', 4)], 
              names=['n', 'v'])
            )
df

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [ ]:
#기본값이 5
df.head()

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [ ]:
df.head(2)

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0

In [ ]:
df.tail()

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [ ]:
df.tail(2)

       a    b     c
n v
e 3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [ ]:
"""
samaple은 특정 비율로 데이터를 불러옴(랜덤하게 가져옴)
frac 의 값은 0.1 부터 1까지 지정을 할 수 있음

"""
df.sample(frac=1)

       a    b     c
n v
e 2  6.0  NaN  12.0
  4  NaN  9.0  12.0
d 2  5.0  8.0  11.0
  1  4.0  7.0  10.0
e 3  6.0  9.0   NaN

In [4]:
"""
sample에는 다양한 매개변수가 있다.
n 매개변수가 들어감 

Randomly select n rows.

"""
df.sample(n=2)

       a    b     c
n v
d 1  4.0  7.0  10.0
e 4  NaN  9.0  12.0

In [10]:

"""
시작하는 인덱스와 끝나는 인덱스를 정해줄 수 있다.

값이 안나오는 이유는 해당 인덱스가 없기 때문이다.
"""

df.iloc[10:20]

Empty DataFrame
Columns: [a, b, c]
Index: []

In [11]:
"""
인덱스 1부터 3까지 가져온다.
"""
df.iloc[1:3]

       a    b     c
n v
d 2  5.0  8.0  11.0
e 2  6.0  NaN  12.0

In [13]:
"""
인덱스 0부터 3까지
"""

df.iloc[:3]

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0

In [14]:
"""
인덱스 3부터 끝까지
"""

df.iloc[3:]

       a    b     c
n v
e 3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [15]:
"""
마지막 인덱스 -2부터 끝까지 가져온다.
"""
df.iloc[-2:]

       a    b     c
n v
e 3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [16]:
df.iloc[:-2]

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0

In [19]:
df = pd.DataFrame({
    'a': [1,10,8,11,-1],
    'b': list('abdce'),
    'c': [1.0,2.0,np.nan,3.0, 4.0]
})
df

    a  b    c
0   1  a  1.0
1  10  b  2.0
2   8  d  NaN
3  11  c  3.0
4  -1  e  4.0

In [20]:
# 가장 큰값
df.nlargest(3, 'a')

    a  b    c
3  11  c  3.0
1  10  b  2.0
2   8  d  NaN

In [21]:

df.nlargest(1, 'a')

    a  b    c
3  11  c  3.0

In [22]:
# 숫자값에서만 사용할 수 있는 함수이다.
# 데이터 타입이 오브젝트이기 때문에 사용할 수 없다.
df.nlargest(1, 'b')

TypeError: ignored

In [23]:
df.nlargest(3, 'c')

    a  b    c
4  -1  e  4.0
3  11  c  3.0
1  10  b  2.0

In [24]:
# 가장 작은값
df.nsmallest(1, 'a')

   a  b    c
4 -1  e  4.0

In [25]:
df.nsmallest(3,'a')

   a  b    c
4 -1  e  4.0
0  1  a  1.0
2  8  d  NaN