<a href="https://colab.research.google.com/github/xersuy/pandas_10min_study/blob/main/pandas_10min_class_05_29.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
import numpy as np
df = pd.DataFrame(
            {
              "a" : [4, 5, 6, 6, np.nan],
              "b" : [7, 8, np.nan, 9, 9],
              "c" : [10, 11, 12,np.nan, 12]
            },
            index = pd.MultiIndex.from_tuples(
              [('d', 1),('d', 2),('e', 2),('e', 3),('e', 4)], 
              names=['n', 'v'])
            )
df

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [5]:
df.head()

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [6]:
df.head(2)

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0

In [7]:
df.tail()

       a    b     c
n v
d 1  4.0  7.0  10.0
  2  5.0  8.0  11.0
e 2  6.0  NaN  12.0
  3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [8]:
df.tail(2)

       a    b     c
n v
e 3  6.0  9.0   NaN
  4  NaN  9.0  12.0

In [15]:
"""
samaple은 랜덤의 값을 가져옴
frac 의 값은 0.1 부터 1까지 지정을 할 수 있음
"""
df.sample(frac=1)

       a    b     c
n v
e 2  6.0  NaN  12.0
  4  NaN  9.0  12.0
d 2  5.0  8.0  11.0
  1  4.0  7.0  10.0
e 3  6.0  9.0   NaN

In [16]:
"""

n 매개변수 
Randomly select n rows.

"""
df.sample(n=1)

       a    b     c
n v
d 1  4.0  7.0  10.0